# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92d75f31dd071db335fa55453ed7c6f590ad1ff519372b8230c9facd80d47f52b8e1e10b16b157743838b285f9f4d8f6dd18c5c9ef21af9c641b288b531d2285

test:
  secret_key_base: 85d695f028566d440e3a03bd2df08127dd14e58ba49d519563fb4311f7dd5e38ce04539ad2a72335e8c1f401a475bfa3dc4267866e35a9275a2a5c3b118de181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
